version: "3"

services:
    node:
        image: "node:11"
        user: "node"
        working_dir: /home/node/app/
        environment:
            - NODE_ENV
        volumes:
            - ./:/home/node/app/
        ports:
            - ${PORT_TEST_CLIENT}:${PORT_TEST_CLIENT}
        command: bash -c "cd client && npm install && npm run generate_assets"
    python:
        build:
            context: .
            dockerfile: python.Dockerfile
        user: "python"
        working_dir: /home/python/app/
        environment:
            - PIPENV_VENV_IN_PROJECT
            - FLASK_ENV
            - FLASK_APP
        volumes:
            - ./:/home/python/app/
        ports:
            - ${PORT_TEST_SERVER}:${PORT_TEST_SERVER}
        command: "pipenv run python_start"
    adminer:
        image: adminer
        environment:
            - ADMINER_PLUGINS
            - PASS_ADMINER
        volumes:
            - ./config/login-password-less.php:/var/www/html/plugins-enabled/login-password-less.php
            - ./website.db:/website.db
        ports:
            - ${PORT_ADMINER}:8080
