version: "3"

services:
    node:
        image: "node:11"
        user: "node"
        working_dir: /home/node/app/
        env_file:
            - .env.node
        volumes:
            - ./:/home/node/app/
        ports:
            - 3000:3000
            - 4200:4200
        command: "npm start"
