version: "3"

services:
    node:
        image: "node:11"
        user: "node"
        working_dir: /home/node/app/
        env_file:
            - .env.node
        volumes:
            - ./:/home/node/app/
        ports:
            - 3000:3000
            - 4200:4200
        command: "npm start"
    python:
        build:
            context: .
            dockerfile: python.dockerfile
        user: "python"
        working_dir: /home/python/app/
        env_file:
            - .env.python
        volumes:
            - ./:/home/python/app/
        ports:
            - 5000:5000
        command: "pipenv run python_start"
    python_debug:
        build:
            context: .
            dockerfile: python.dockerfile
        user: "python"
        working_dir: /home/python/app/
        env_file:
            - .env.python
        volumes:
            - ./:/home/python/app/
        ports:
            - 5001:5001
        command: "pipenv run python_debug_start"
