version: "3"

services:
    node:
        image: "node:11"
        user: "node"
        working_dir: /home/node/app/
        env_file:
            - .env.node
        volumes:
            - ./:/home/node/app/
        ports:
            - ${PORT_TEST_CLIENT}:${PORT_TEST_CLIENT}
        command: bash -c "cd client && npm install && npm run generate_assets"
    python:
        build:
            context: .
            dockerfile: python.dockerfile
        user: "python"
        working_dir: /home/python/app/
        env_file:
            - .env.python
        volumes:
            - ./:/home/python/app/
        ports:
            - ${PORT_TEST_SERVER}:${PORT_TEST_SERVER}
        command: "pipenv run python_start"
    python_debug:
        build:
            context: .
            dockerfile: python.dockerfile
        user: "python"
        working_dir: /home/python/app/
        env_file:
            - .env.python
        volumes:
            - ./:/home/python/app/
        ports:
            - ${PORT_DEBUG}:${PORT_DEBUG}
        command: "pipenv run -- python_debug_start --bind 0.0.0.0:${PORT_DEBUG} debug_wsgi:APP"
