version: "3"

services:
    node:
        image: "node:11"
        user: "node"
        working_dir: /home/node/app/
        env_file:
            - .env.node
        volumes:
            - ./:/home/node/app/
        ports:
            - ${TEST_CLIENT_PORT}:${TEST_CLIENT_PORT}
        command: bash -c "cd client && npm install && npm run generate_assets"
    python:
        build:
            context: .
            dockerfile: python.dockerfile
        user: "python"
        working_dir: /home/python/app/
        env_file:
            - .env.python
        volumes:
            - ./:/home/python/app/
        ports:
            - ${TEST_SERVER_PORT}:${TEST_SERVER_PORT}
        command: "pipenv run python_start"
    python_debug:
        build:
            context: .
            dockerfile: python.dockerfile
        user: "python"
        working_dir: /home/python/app/
        env_file:
            - .env.python
        volumes:
            - ./:/home/python/app/
        ports:
            - ${DEBUG_PORT}:${DEBUG_PORT}
        command: "pipenv run -- python_debug_start --bind 0.0.0.0:${DEBUG_PORT} debug_wsgi:APP"
