#!/usr/bin/python3

"""Minimal python client for pylint.

This client:
* Receives arguments from stdin.
* Transforms arguments to appropriate format.
* Finally passes arguments to server.
* Waits for server response.

The response is handed back through stdout.

NOTE: The client has to be run from host machine, not from a container.
"""
#pylint: disable=E0401
import sys
import pathlib
import requests

from definitions import PROJECT_PATH

if __name__ == '__main__':
    # change to relative path
    sys.argv[-1] = str(pathlib.Path(sys.argv[-1]).relative_to(PROJECT_PATH))
    # remove filename
    sys.argv.pop(0)
    # the debugger_container
    with open(PROJECT_PATH/'.env', 'r') as env:
        for line in env:
            if line.startswith('DEBUG_PORT'):
                PORT = line.replace('DEBUG_PORT', '').replace('=', '').strip()
                break
    DEBUGGER_RESPONSE = requests.post(
        'http://localhost:'+PORT,
        json=sys.argv,
    )
    sys.stdout.write(str(DEBUGGER_RESPONSE.text))
    sys.exit(0)
